# Generated by Django 3.2.8 on 2024-11-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_servicecatogarys_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='users',
            name='citizenship',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='users',
            name='covid_19_vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='language_prefered',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='workers',
            name='age',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='workers',
            name='citizenship',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='workers',
            name='covid_19_vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workers',
            name='language_prefered',
            field=models.CharField(default='', max_length=150),
        ),
    ]
